### PR TITLE
Fix parsing xml attribute with prefix

### LINKED ISSUE #54: Error in xml parameter with attributes
**Description:**
```
<Document>
    <FIToFICstmrCdtTrf>
        <GrpHdr>
            <MsgId>123489</MsgId>
            <CreDtTm>0111522180</CreDtTm>
            <NbOfTxs>1</NbOfTxs>
            <SttlmInf>
                <SttlmMtd>INDA</SttlmMtd>
            </SttlmInf>
        </GrpHdr>
        <CdtTrfTxInf>
            <PmtId>
                <EndToEndId>12348912a456789123</EndToEndId>
            </PmtId>
            <IntrBkSttlmAmt Ccy="USD">500000</IntrBkSttlmAmt>
            <ChrgBr>DEBT</ChrgBr>
            <Dbtr>
                <number>1</number>
            </Dbtr>
            
            <CdtrAgt>
                <FinInstnId>100009</FinInstnId>
            </CdtrAgt>
        </CdtTrfTxInf>
        
    </FIToFICstmrCdtTrf>
</Document>
```

If we set an XML as a parameter that has an attribute, the connector does not work.

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose

Fixes #54

### CODE REVIEW

File: native/src/main/java/io/ballerina/stdlib/mi/OMElementConverter.java [hunk 1]
```diff
@@ -77,12 +77,8 @@ private static QName getQNameOMElement(OMElement omElement) {
...
     private static QName getQNameOMAttribute(OMAttribute omAttribute) {
         // If prefix is not provided test case will fail
-        if (omAttribute.getPrefix() == null) {
-            return new QName(omAttribute.getNamespaceURI(), omAttribute.getLocalName());
-        } else {
-            return new QName(omAttribute.getNamespaceURI(), omAttribute.getLocalName(), omAttribute.getPrefix());
-        }
-
+        QName qName = omAttribute.getQName();
+        return new QName(qName.getNamespaceURI(), qName.getLocalPart(), qName.getPrefix());
```
Comment (hasithaa) [inline native/src/main/java/io/ballerina/stdlib/mi/OMElementConverter.java]: Why we can't use above qname as the return value?

Comment (KavinduZoysa) [reply native/src/main/java/io/ballerina/stdlib/mi/OMElementConverter.java]: Fixed

**Review by hasithaa — APPROVED** [review]
